---
title: "Simulation Output"
output: html_document
---

##Mean parameters: original code
```{r echo=FALSE}
rm(list=ls())
library(knitr)
library(kableExtra)
load("Code17b_choice_s1-88_iter100.Rdata")

#SDI 1:39, control 40:88

##Table.3
dat_sdi <- parstack[1:39,1:3,5]
dat_control <- parstack[40:88,1:3,5]
mean_s <- apply(dat_sdi,2,mean)
mean_c <- apply(dat_control,2,mean)
median_s <- apply(dat_sdi,2,median)
median_c <- apply(dat_control,2, median)
sd_s <- apply(dat_sdi, 2, sd)
sd_c <- apply(dat_control, 2, sd)

t3 <- rbind(mean_c,mean_s,median_c,median_s,sd_c,sd_s)
t3 <- as.data.frame(t3)



kable(t3, format = "html", caption = "Original Code", align="l") %>%
  kable_styling(bootstrap_options = "striped",
                full_width = F) %>%
  add_header_above(c("Group"=1, "Parameters" = 3)) %>%
  group_rows("Mean", 1,2) %>%
  group_rows("Median", 3,4) %>%
  group_rows("Standard deviation", 5,6)



```

##Mean parameters: DY code
```{r echo=FALSE}
load("DY_MLE.Rdata")

#Control 1:49, SDI 50:88

##Table.3
dat_control <- parstack[1:49,1:3,5]
dat_sdi <- parstack[50:88,1:3,5]
mean_s <- apply(dat_sdi,2,mean)
mean_c <- apply(dat_control,2,mean)
median_s <- apply(dat_sdi,2,median)
median_c <- apply(dat_control,2, median)
sd_s <- apply(dat_sdi, 2, sd)
sd_c <- apply(dat_control, 2, sd)

t3 <- rbind(mean_c,mean_s,median_c,median_s,sd_c,sd_s)
t3 <- as.data.frame(t3)



kable(t3, format = "html", caption = "DY Code", align="l") %>%
  kable_styling(bootstrap_options = "striped",
                full_width = F) %>%
  add_header_above(c("Group"=1, "Parameters" = 3)) %>%
  group_rows("Mean", 1,2) %>%
  group_rows("Median", 3,4) %>%
  group_rows("Standard deviation", 5,6)



```



##Mean parameters: deleting i
The reason why it has larger sd with d is that here, SDI group had 3 more individuals whose d estimation is 5 instead of 0-1.
Compared to original result, deleting i creates 5 individuals whose d estimation is very(difference over 3) different.
```{r echo=FALSE}
load("constrained.RData")

##Table.3
t3 <- rbind(mean_par, median_par, sd_par) #duplicated rownames
rownames(t3) <- c("mean_c","mean_s","median_c","median_s","sd_c","sd_s")
colnames(t3) <- c("r","p","d")
t3 <- as.data.frame(t3)



kable(t3, format = "html", caption = "Constrained Code", align="l") %>%
  kable_styling(bootstrap_options = "striped",
                full_width = F) %>%
  add_header_above(c("Group"=1, "Parameters" = 3)) %>%
  group_rows("Mean", 1,2) %>%
  group_rows("Median", 3,4) %>%
  group_rows("Standard deviation", 5,6)


```



