
#Replicating Tables within the Paper  


####Table.2 Mean BIC for 12 Models(r is free, values not included)
```{r}
load("Code17b_WCST S_s1-3_iter100.Rdata")
library(knitr)
library(kableExtra)
    options(knitr.kable.NA = '')

meanBIC <- colMeans(BICfinalmat)
r=rep(c("free","fixed"),12)
p=c(rep("free",12),rep("fixed",12))
d=rep(c(rep("free",6),rep("fixed",6)),2)
f=rep(c(rep("free",2),rep(0,2),rep(1,2)),4)
t2 <- data.frame(meanBIC, r, p, d, f)
t2_nr <- t2[t2$r=="free",-2]

vars <- t2_nr[,1]
v1 <- c(vars[c(1,4,7,10)])
v2 <- c(vars[c(2,5,8,11)])
v3 <- c(vars[c(3,6,9,12)])
vars <- data.frame(v1, v2, v3, c(mean(deckbaseBIC),NA,NA,NA))
colnames(vars)<-c("f free", "f = 0", "f = 1", "Baseline model")

row_vars <- data.frame(v1=c(rep("p free", 2),rep("p = r", 2)),v2=c(rep(c("d free", "d = 1"),2)),vars)

kable(row_vars, format="html", col.names=c("","",colnames(vars)), caption="Table 2", algin="l") %>%
  kable_styling(bootstrap_options = "striped",
                full_width = F) %>%
  collapse_rows(columns=1:2) %>%
  add_header_above(c("Model constraints"=6))
  


```


  
####Fig.2 Observed Scores for categories completed/presev error/nonperserv error/set failures
```{r}

#calculate categories completed

subj_catecom <- c()
for (subj in subjectsmodeled){
  inf <- data.frame(rawdatamat[subj,129:(128+lengthvec[subj])])
  catecom=0
  locvec <- which(inf==0)
  
  for(i in 1:(length(locvec)-1)) {
    if(sum(inf[locvec[i]:locvec[i+1]])>=10){catecom=catecom+1}
    if((i == (length(locvec)-1)) & sum(inf[locvec[i+1]:length(inf)])==10){catecom=catecom+1}
  }
  subj_catecom[subj] <- catecom
}

  ##data frame
  sdi_catecom <- mean(subj_catecom[1:39])
  control_catecom <- mean(subj_catecom[40:88])
  mean_catecom <- c(sdi_catecom, control_catecom)
  subj_catecom_dat <- data.frame(group=c("SDI", "Control"), score=rep("Categoreis Completed",2), value=mean_catecom)

#persev.error
print("Not Ready Yet...have to see how to calculate this error")

#nonpersev.error
print("Not Ready Yet...have to see how to calculate this error")

#failure to maintain set
subj_failure <- c()
for (subj in subjectsmodeled){
  inf <- data.frame(rawdatamat[subj,129:(128+lengthvec[subj])])
  failure=0
  locvec <- which(inf==0)
  
  for(i in 1:(length(locvec)-1)) {
    if((sum(inf[locvec[i]:locvec[i+1]])<10 & sum(inf[locvec[i]:locvec[i+1]]) >= 5)){failure = failure+1}
    
  }
  subj_failure[subj] <- failure
}

  ##data frame
  sdi_failure <- mean(subj_failure[1:39])
  control_failure <- mean(subj_failure[40:88])
  mean_failure <- c(sdi_failure, control_failure)
  subj_failure_dat <- data.frame(group=c("SDI", "Control"), score=rep("Set Failures",2), value=mean_failure)

#integrate
catecom_sd <- c(sd(subj_catecom[1:39]),sd(subj_catecom[40:88]))
failure_sd <- c(sd(subj_failure[1:39]),sd(subj_failure[40:88]))
sd <- c(catecom_sd, failure_sd)
total <- rbind(subj_catecom_dat, subj_failure_dat); total <- cbind(total, sd)

```

####graph of the errors
```{r}
library(ggplot2)

bp <- ggplot(total, aes(x=score, y=value, fill=group)) + 
   geom_bar(colour="black", stat="identity", position=position_dodge(), width=0.5) +
  geom_errorbar(aes(ymin=value-sd, ymax=value+sd), width=0.1,
                 position=position_dodge(.5))

bp + labs(title="(A) Observed Data", x="", y="Observed Value") +
   scale_fill_manual(values=c('black','white'), guide = guide_legend(title=NULL)) + 
   theme_classic() +
   theme(legend.position = c(0.75,0.75)) 
   #scale_y_continuous(expand = c(0, 0), limits = c(0, 6.5)) #for deleting the space of x-axis. It cuases problem now because of 0 value of "Set Failures"

bp
```


  
####Fig.2 Model Simulation
```{r echo=FALSE}
print("Not Ready Yet...do not now how to simulate a model right now")
```


  
####Table.3 Mean Parameters for rpd1 Model
```{r}
load("rpd1_Code17b_choice_s1-88_iter100.Rdata")
pars_rpd1 <- cbind(parstack[,,5],group=factor(c(rep(2, 39),rep(1, 49))))
pars_rpd1 <- pars_rpd1[c(40:88,1:39),]
gname <- c("Control", "SDI")

##Table 3
meanPars <- aggregate(.~group, data=as.data.frame(pars_rpd1), FUN=mean)
medPars <- aggregate(.~group, data=as.data.frame(pars_rpd1), FUN=median)
sdPars <- aggregate(.~group, data=as.data.frame(pars_rpd1), FUN=sd)
pars_summary <- rbind(round(meanPars,2), round(medPars,2), round(sdPars,2))
pars_summary[,1] <- factor(rep(gname,3))


library(knitr)
library(kableExtra)
kable(pars_summary, format = "html",col.names = c("", "r", "p", "d", "i"), caption = "Table 3", align="l") %>%
  kable_styling(bootstrap_options = "striped",
                full_width = F) %>%
  add_header_above(c("Group"=1, "Parameters" = 4)) %>%
  group_rows("Mean", 1,2) %>% group_rows("Median",3,4) %>% group_rows("Standard deviation", 5,6)



```
